name: build-react
on:
  pull_request:
    branches:
      - master

jobs:
  build-react:
    name: Build React App
    runs-on: linux
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest
      - name: Install dependencies
        run: npm install
      - name: Build React App
        run: npm run build
