# taken and modified from https://github.com/UniversalDataTool/universal-data-tool/blob/master/.github/workflows/release-on-master.yml
name: deploy-gh-pages
on:
  push:
    branches:
      - master
jobs:
  release:
    name: Release
    runs-on: linux
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest
      - name: Install dependencies
        run: npm install
#      - name: Build NPM package
#        run: npm run build:lib
#      - name: Release
#        env:
#          GITHUB_TOKEN: ${{ secrets.RELEASE_GITHUB_TOKEN }}
#          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
#        run: npx semantic-release
      - name: Publish github pages
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/shibby64.github.io.git
          npx gh-pages -d build -u "github-actions-bot <support+actions@github.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
